version: '3.8'

services:
  reservation-service:
    build:
      context: .
    container_name: reservation-service
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      #- db
      - redis

  

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: